"""Configuration and data containers for the public ScenarioMiner SDK."""

from __future__ import annotations

from dataclasses import dataclass

from diffav.core.config import FactorizedBackboneHyperparams, validate_positive
from diffav.core.constants import WOD_FUTURE_STEPS
from diffav.core.types import ScenarioMetadata, SceneContext, TrajectoryPrediction


@dataclass(frozen=True, slots=True, kw_only=True)
class MinerConfig(FactorizedBackboneHyperparams):
    """Configuration for ScenarioMiner.

    Attributes:
        model_path: Path to the checkpoint directory. Empty string means
            no checkpoint is loaded (model initialised with random weights,
            useful for testing and development).
        batch_size: Number of scenarios per generation batch.
        max_agents: Maximum agents per generated scene.
        prediction_horizon: Future timesteps to predict.
        context_dim: Scene context embedding dimension. Must match the
            ``context_dim`` of the loaded TrajectoryDiffusionModel.
        num_diffusion_steps: Diffusion reverse-process steps for
            ``TrajectoryDiffusionModel.sample()``. Lower values are faster
            but lower quality. Default 100 matches the training
            configuration (``scripts/train_wod.py``) and reference
            trajectory-diffusion practice; use a smaller value (e.g. 10)
            for tests.
        hidden_dim: Transformer hidden dimension of the underlying model.
        num_blocks: Factorized backbone blocks of the underlying model.
        num_temporal_layers: Temporal attention sublayers per block.
        num_social_layers: Social attention sublayers per block.
        use_social_interaction: Whether agents attend across one another.
        num_heads: Attention heads of the underlying model.
    """

    model_path: str = ""
    batch_size: int = 32
    max_agents: int = 32
    prediction_horizon: int = WOD_FUTURE_STEPS
    context_dim: int = 128
    num_diffusion_steps: int = 100

    def __post_init__(self) -> None:
        """Validate configuration constraints."""
        validate_positive("batch_size", self.batch_size)
        validate_positive("max_agents", self.max_agents)
        validate_positive("prediction_horizon", self.prediction_horizon)
        validate_positive("context_dim", self.context_dim)
        validate_positive("num_diffusion_steps", self.num_diffusion_steps)
        validate_positive("hidden_dim", self.hidden_dim)
        validate_positive("num_blocks", self.num_blocks)
        validate_positive("num_temporal_layers", self.num_temporal_layers)
        validate_positive("num_social_layers", self.num_social_layers)
        validate_positive("num_heads", self.num_heads)


@dataclass(frozen=True, slots=True, kw_only=True)
class Scenario:
    """Immutable container for a generated driving scenario.

    Attributes:
        context: The scene context (ego + agents + map).
        predictions: Reference trajectory predictions generated by the
            ScenarioMiner model.
        metadata: Scenario identification and tags.
    """

    context: SceneContext
    predictions: TrajectoryPrediction
    metadata: ScenarioMetadata


@dataclass(frozen=True, slots=True, kw_only=True)
class FailureCase:
    """Immutable record of a planner failure found by adversarial search.

    Attributes:
        scenario: The adversarial scenario that caused the failure.
        failure_mode: Human-readable label for the failure type (e.g.
            ``"kinematics_violation"``, ``"collision_risk"``).
        severity: Non-negative numeric severity score from physics loss.
    """

    scenario: Scenario
    failure_mode: str
    severity: float

    def __post_init__(self) -> None:
        """Validate field constraints."""
        # severity=0.0 is valid (no violation yet), so validate_positive is not used here
        if self.severity < 0.0:
            msg = f"severity must be non-negative, got {self.severity}"
            raise ValueError(msg)
        if not self.failure_mode:
            msg = "failure_mode must be a non-empty string"
            raise ValueError(msg)
