"""Core domain types, constants, and shared configuration validators."""

from diffav.core.config import (
    VALID_SPLITS,
    validate_positive,
    validate_transformer_fields,
)
from diffav.core.constants import (
    FeatureEstimateConfig,
    HistogramEstimateConfig,
    KINEMATIC_POSITION_RESIDUAL_TOLERANCE_M2,
    KinematicEnvelope,
    WOD_CURRENT_TIME_INDEX,
    WOD_FULL_SCENARIO_STEPS,
    WOD_FUTURE_STEPS,
    WOD_HISTORY_STEPS,
    WOD_STEP_DURATION_SECONDS,
    WOSAC_2025_KINEMATIC_ENVELOPE,
    WOSAC_2025_METAMETRIC_CONFIG,
    WOSAC_N_ROLLOUTS,
    WosacMetametricConfig,
)
from diffav.core.geometry import (
    mean_offroad_penalty,
    RoadEdges,
    signed_distance_to_polylines,
    signed_distances_to_road_edges,
    stack_polylines,
    stack_polylines_fixed,
)
from diffav.core.training_utils import nan_safe_gradients
from diffav.core.types import (
    AgentState,
    AgentType,
    DatasetMode,
    Density,
    FusionStrategy,
    LossType,
    MapFeature,
    MapFeatureType,
    MetricsReport,
    Modality,
    ModalityMode,
    NoiseScheduleType,
    PhysicsScheduleType,
    ScenarioMetadata,
    ScenarioType,
    SceneContext,
    TrajectoryPrediction,
)


__all__ = [
    "AgentState",
    "AgentType",
    "FeatureEstimateConfig",
    "HistogramEstimateConfig",
    "KINEMATIC_POSITION_RESIDUAL_TOLERANCE_M2",
    "KinematicEnvelope",
    "WOD_CURRENT_TIME_INDEX",
    "WOD_FULL_SCENARIO_STEPS",
    "WOD_FUTURE_STEPS",
    "WOD_HISTORY_STEPS",
    "WOD_STEP_DURATION_SECONDS",
    "WOSAC_2025_KINEMATIC_ENVELOPE",
    "WOSAC_2025_METAMETRIC_CONFIG",
    "WosacMetametricConfig",
    "WOSAC_N_ROLLOUTS",
    "DatasetMode",
    "Density",
    "FusionStrategy",
    "LossType",
    "mean_offroad_penalty",
    "nan_safe_gradients",
    "NoiseScheduleType",
    "PhysicsScheduleType",
    "RoadEdges",
    "signed_distance_to_polylines",
    "signed_distances_to_road_edges",
    "stack_polylines",
    "stack_polylines_fixed",
    "MapFeature",
    "MapFeatureType",
    "MetricsReport",
    "Modality",
    "ModalityMode",
    "ScenarioMetadata",
    "ScenarioType",
    "SceneContext",
    "TrajectoryPrediction",
    "VALID_SPLITS",
    "validate_positive",
    "validate_transformer_fields",
]
